use_frameworks!

platform :ios, '8.0'

target 'WPBaseTableView_Example' do
  pod 'WPBaseTableView', :path => '../'

  pod 'WPChained','0.1.1'
  
  target 'WPBaseTableView_Tests' do
    inherit! :search_paths

    
  end
end
